// Generated by CoffeeScript 1.6.3
(function() {
  var expect;

  expect = chai.expect;

  describe('FormLogic', function() {
    var $form, errorClass;
    $form = $('#signupForm');
    errorClass = 'has-error';
    afterEach(function() {
      $('#signupForm').find('input, select, textarea').not('input[type="submit"]').val('').removeClass('has-error');
      return $('.error').remove();
    });
    describe('constructor', function() {
      return it('exists in the global scope', function() {
        var fl;
        fl = new FormLogic;
        return expect(fl).to.exist;
      });
    });
    return describe('validators', function() {
      return it('validates a required value', function() {
        $('#signupForm input[type="submit"]').click();
        return setTimeout(function() {
          return expect($input.hasClass(errorClass)).to.be["true"];
        }, 50);
      });
    });
  });

}).call(this);
