// Generated by CoffeeScript 1.6.3
(function() {
  var expect;

  expect = chai.expect;

  describe('FormLogic', function() {
    var $form, errorClass;
    $form = $('#signupForm');
    errorClass = 'has-error';
    afterEach(function() {
      $('#signupForm').find('input, select, textarea').not('input[type="submit"]').val('').removeClass('has-error');
      return $('.error').remove();
    });
    describe('constructor', function() {
      return it('exists in the global scope', function() {
        var fl;
        fl = new FormLogic;
        return expect(fl).to.exist;
      });
    });
    describe('validators', function() {
      it('validates a required value');
      it('validates email format');
      it('validates a phone number');
      it('validates a minimum number');
      it('validates a maximum number');
      it('validates a minimum length');
      it('validates a maximum length');
      it('validates that the value is a number');
      it('validates a confirmation value');
      it('does not validate hidden input elements');
      return it('validates hidden elements if given the data-force-validation option');
    });
    return describe('errors', function() {
      it('creates a default div after the input element when no options are specified');
      return it('opts for the data-error-target if specified');
    });
  });

}).call(this);
