// Generated by CoffeeScript 1.6.3
(function() {
  var fl;

  this.FormLogic = (function() {
    function FormLogic() {
      console.log('yo');
      this.validators = {};
      this.buildDefaultValidators();
      this.setupHandlers();
    }

    FormLogic.prototype.validator = function(name, func) {
      if (!func || typeof func !== 'function') {
        throw 'The second argument you passed to FormLogic.validator() was not a function';
      }
      return this.validators[name] = func;
    };

    FormLogic.prototype.setupHandlers = function() {
      var input, _i, _len, _ref, _results;
      _ref = $('[data-validate');
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        input = _ref[_i];
        $(input).blur(this.runValidators);
        _results.push($(input).focus(this.clearErrors));
      }
      return _results;
    };

    FormLogic.prototype.runValidators = function(e) {
      var $input, name, vNames, vString, _i, _len, _results;
      $input = $(this);
      if (($input.is(':hidden') || $input.is(':submit')) && !$input.data('force-validation')) {
        return;
      }
      vString = $input.data('validate');
      if (typeof vString !== 'string') {
        return;
      }
      vNames = vString.split(' ');
      _results = [];
      for (_i = 0, _len = vNames.length; _i < _len; _i++) {
        name = vNames[_i];
        if (!this.validators[name]) {
          continue;
        }
        if (!this.validators.name($input)) {
          _results.push(this.showError($input, name));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    FormLogic.prototype.clearErrors = function(e) {};

    FormLogic.prototype.showError = function($input, name) {};

    FormLogic.prototype.buildDefaultValidators = function() {
      return this.validator('required', function($input) {
        var name, option, _i, _len, _ref;
        console.log('validating required');
        if ($input.attr('type') === 'radio' || $input.attr('type') === 'checkbox') {
          name = $input.attr('name');
          _ref = $('[name="' + name + '"]');
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            option = _ref[_i];
            if ($(option).is(':checked')) {
              return;
            }
          }
          return showError($input, 'required');
        } else {
          if ($input.val() === '') {
            return showError($input, 'required');
          }
        }
      });
    };

    return FormLogic;

  })();

  fl = new FormLogic;

}).call(this);
